<a href="https://colab.research.google.com/github/yakaralar/IE492/blob/master/bitirme_notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive

In [0]:
import os
import glob
import shutil
os.listdir()

['.config', 'drive', 'sample_data']

In [0]:
os.listdir("drive/My Drive/colab_datas/IE 492")

['Comparison of methods.pdf',
 '1-s2.0-S1364032114000914-main.pdf',
 '1-s2.0-S0360544209002539-main.pdf',
 '1-s2.0-S1876610211043116-main.pdf',
 '1-s2.0-S0305048311001423-main.pdf',
 'weather_turkey_processed.zip',
 'Meta_L_makaleler',
 'all_data.feather',
 'UECM-15012015-20022020.csv',
 'RealTimeConsumption-01122014-09032020.csv',
 'updated_support-date_based_information.r',
 'ozel_gunler',
 'RealTimeConsumption_unholidayized.csv']

In [0]:
shutil.copy("drive/My Drive/colab_datas/IE 492/weather_turkey_processed.zip","./")
!unzip weather_turkey_processed.zip

Archive:  weather_turkey_processed.zip
   creating: weather_turkey_processed/
  inflating: weather_turkey_processed/36_26.5.csv
  inflating: weather_turkey_processed/38.5_42.csv
  inflating: weather_turkey_processed/36_26.csv
  inflating: weather_turkey_processed/36_27.5.csv
  inflating: weather_turkey_processed/36_27.csv
  inflating: weather_turkey_processed/36_28.5.csv
  inflating: weather_turkey_processed/36_28.csv
  inflating: weather_turkey_processed/36_29.5.csv
  inflating: weather_turkey_processed/36_29.csv
  inflating: weather_turkey_processed/36_30.5.csv
  inflating: weather_turkey_processed/36_30.csv
  inflating: weather_turkey_processed/36_31.5.csv
  inflating: weather_turkey_processed/36_31.csv
  inflating: weather_turkey_processed/36_32.5.csv
  inflating: weather_turkey_processed/36_32.csv
  inflating: weather_turkey_processed/36_33.5.csv
  inflating: weather_turkey_processed/36_33.csv
  inflating: weather_turkey_processed/36_34.5.csv
  inflating: weather_turkey_processed/36_34.csv
  inflating: weather_turkey_processed/36_35.5.csv
  inflating: weather_turkey_processed/36_35.csv
  inflating: weather_turkey_processed/36_36.5.csv
  inflating: weather_turkey_processed/36_36.csv
  inflating: weather_turkey_processed/36_37.5.csv
  inflating: weather_turkey_processed/36_37.csv
  inflating: weather_turkey_processed/36_38.5.csv
  inflating: weather_turkey_processed/36_38.csv
  inflating: weather_turkey_processed/36_39.5.csv
  inflating: weather_turkey_processed/36_39.csv
  inflating: weather_turkey_processed/36_40.5.csv
  inflating: weather_turkey_processed/36_40.csv
  inflating: weather_turkey_processed/36_41.5.csv
  inflating: weather_turkey_processed/36_41.csv
  inflating: weather_turkey_processed/36_42.5.csv
  inflating: weather_turkey_processed/36_42.csv
  inflating: weather_turkey_processed/36_43.5.csv
  inflating: weather_turkey_processed/36_43.csv
  inflating: weather_turkey_processed/36_44.5.csv
  inflating: weather_turkey_processed/36_44.csv
  inflating: weather_turkey_processed/36_45.csv
  inflating: weather_turkey_processed/36.5_26.5.csv
  inflating: weather_turkey_processed/36.5_26.csv
  inflating: weather_turkey_processed/36.5_27.5.csv
  inflating: weather_turkey_processed/36.5_27.csv
  inflating: weather_turkey_processed/36.5_28.5.csv
  inflating: weather_turkey_processed/36.5_28.csv
  inflating: weather_turkey_processed/36.5_29.5.csv
  inflating: weather_turkey_processed/36.5_29.csv
  inflating: weather_turkey_processed/36.5_30.5.csv
  inflating: weather_turkey_processed/36.5_30.csv
  inflating: weather_turkey_processed/36.5_31.5.csv
  inflating: weather_turkey_processed/36.5_31.csv
  inflating: weather_turkey_processed/36.5_32.5.csv
  inflating: weather_turkey_processed/36.5_32.csv
  inflating: weather_turkey_processed/36.5_33.5.csv
  inflating: weather_turkey_processed/36.5_33.csv
  inflating: weather_turkey_processed/36.5_34.5.csv
  inflating: weather_turkey_processed/36.5_34.csv
  inflating: weather_turkey_processed/36.5_35.5.csv
  inflating: weather_turkey_processed/36.5_35.csv
  inflating: weather_turkey_processed/36.5_36.5.csv
  inflating: weather_turkey_processed/36.5_36.csv
  inflating: weather_turkey_processed/36.5_37.5.csv
  inflating: weather_turkey_processed/36.5_37.csv
  inflating: weather_turkey_processed/36.5_38.5.csv
  inflating: weather_turkey_processed/36.5_38.csv
  inflating: weather_turkey_processed/36.5_39.5.csv
  inflating: weather_turkey_processed/36.5_39.csv
  inflating: weather_turkey_processed/36.5_40.5.csv
  inflating: weather_turkey_processed/36.5_40.csv
  inflating: weather_turkey_processed/36.5_41.5.csv
  inflating: weather_turkey_processed/36.5_41.csv
  inflating: weather_turkey_processed/36.5_42.5.csv
  inflating: weather_turkey_processed/36.5_42.csv
  inflating: weather_turkey_processed/36.5_43.5.csv
  inflating: weather_turkey_processed/36.5_43.csv
  inflating: weather_turkey_processed/36.5_44.5.csv
  inflating: weather_turkey_processed/36.5_44.csv
  inflating: weather_turkey_processed/36.5_45.csv
  inflating: weather_turkey_processed/37_26.5.csv
  inflating: weather_turkey_processed/37_26.csv
  inflating: weather_turkey_processed/37_27.5.csv
  inflating: weather_turkey_processed/37_27.csv
  inflating: weather_turkey_processed/37_28.5.csv
  inflating: weather_turkey_processed/37_28.csv
  inflating: weather_turkey_processed/37_29.5.csv
  inflating: weather_turkey_processed/37_29.csv
  inflating: weather_turkey_processed/37_30.5.csv
  inflating: weather_turkey_processed/37_30.csv
  inflating: weather_turkey_processed/37_31.5.csv
  inflating: weather_turkey_processed/37_31.csv
  inflating: weather_turkey_processed/37_32.5.csv
  inflating: weather_turkey_processed/37_32.csv
  inflating: weather_turkey_processed/37_33.5.csv
  inflating: weather_turkey_processed/37_33.csv
  inflating: weather_turkey_processed/37_34.5.csv
  inflating: weather_turkey_processed/37_34.csv
  inflating: weather_turkey_processed/37_35.5.csv
  inflating: weather_turkey_processed/37_35.csv
  inflating: weather_turkey_processed/37_36.5.csv
  inflating: weather_turkey_processed/37_36.csv
  inflating: weather_turkey_processed/37_37.5.csv
  inflating: weather_turkey_processed/37_37.csv
  inflating: weather_turkey_processed/37_38.5.csv
  inflating: weather_turkey_processed/37_38.csv
  inflating: weather_turkey_processed/37_39.5.csv
  inflating: weather_turkey_processed/37_39.csv
  inflating: weather_turkey_processed/37_40.5.csv
  inflating: weather_turkey_processed/37_40.csv
  inflating: weather_turkey_processed/37_41.5.csv
  inflating: weather_turkey_processed/37_41.csv
  inflating: weather_turkey_processed/37_42.5.csv
  inflating: weather_turkey_processed/37_42.csv
  inflating: weather_turkey_processed/37_43.5.csv
  inflating: weather_turkey_processed/37_43.csv
  inflating: weather_turkey_processed/37_44.5.csv
  inflating: weather_turkey_processed/37_44.csv
  inflating: weather_turkey_processed/37_45.csv
  inflating: weather_turkey_processed/37.5_26.5.csv
  inflating: weather_turkey_processed/37.5_26.csv
  inflating: weather_turkey_processed/37.5_27.5.csv
  inflating: weather_turkey_processed/37.5_27.csv
  inflating: weather_turkey_processed/37.5_28.5.csv
  inflating: weather_turkey_processed/37.5_28.csv
  inflating: weather_turkey_processed/37.5_29.5.csv
  inflating: weather_turkey_processed/37.5_29.csv
  inflating: weather_turkey_processed/37.5_30.5.csv
  inflating: weather_turkey_processed/37.5_30.csv
  inflating: weather_turkey_processed/37.5_31.5.csv
  inflating: weather_turkey_processed/37.5_31.csv
  inflating: weather_turkey_processed/37.5_32.5.csv
  inflating: weather_turkey_processed/37.5_32.csv
  inflating: weather_turkey_processed/37.5_33.5.csv
  inflating: weather_turkey_processed/37.5_33.csv
  inflating: weather_turkey_processed/37.5_34.5.csv
  inflating: weather_turkey_processed/37.5_34.csv
  inflating: weather_turkey_processed/37.5_35.5.csv
  inflating: weather_turkey_processed/37.5_35.csv
  inflating: weather_turkey_processed/37.5_36.5.csv
  inflating: weather_turkey_processed/37.5_36.csv
  inflating: weather_turkey_processed/37.5_37.5.csv
  inflating: weather_turkey_processed/37.5_37.csv
  inflating: weather_turkey_processed/37.5_38.5.csv
  inflating: weather_turkey_processed/37.5_38.csv
  inflating: weather_turkey_processed/37.5_39.5.csv
  inflating: weather_turkey_processed/37.5_39.csv
  inflating: weather_turkey_processed/37.5_40.5.csv
  inflating: weather_turkey_processed/38_26.5.csv
  inflating: weather_turkey_processed/37.5_40.csv
  inflating: weather_turkey_processed/37.5_41.5.csv
  inflating: weather_turkey_processed/37.5_41.csv
  inflating: weather_turkey_processed/37.5_42.5.csv
  inflating: weather_turkey_processed/37.5_42.csv
  inflating: weather_turkey_processed/37.5_43.5.csv
  inflating: weather_turkey_processed/37.5_43.csv
  inflating: weather_turkey_processed/37.5_44.5.csv
  inflating: weather_turkey_processed/37.5_44.csv
  inflating: weather_turkey_processed/37.5_45.csv
  inflating: weather_turkey_processed/38_26.csv
  inflating: weather_turkey_processed/38_27.5.csv
  inflating: weather_turkey_processed/38_27.csv
  inflating: weather_turkey_processed/40.5_28.5.csv
  inflating: weather_turkey_processed/38_28.5.csv
  inflating: weather_turkey_processed/38_28.csv
  inflating: weather_turkey_processed/38_29.5.csv
  inflating: weather_turkey_processed/38_29.csv
  inflating: weather_turkey_processed/38_30.5.csv
  inflating: weather_turkey_processed/38_30.csv
  inflating: weather_turkey_processed/38_31.5.csv
  inflating: weather_turkey_processed/38_31.csv
  inflating: weather_turkey_processed/38_32.5.csv
  inflating: weather_turkey_processed/38_32.csv
  inflating: weather_turkey_processed/38_33.5.csv
  inflating: weather_turkey_processed/38_33.csv
  inflating: weather_turkey_processed/38_34.5.csv
  inflating: weather_turkey_processed/38_34.csv
  inflating: weather_turkey_processed/38_35.5.csv
  inflating: weather_turkey_processed/38_35.csv
  inflating: weather_turkey_processed/38_36.5.csv
  inflating: weather_turkey_processed/38_36.csv
  inflating: weather_turkey_processed/38_37.5.csv
  inflating: weather_turkey_processed/38.5_40.csv
  inflating: weather_turkey_processed/38_37.csv
  inflating: weather_turkey_processed/38_38.5.csv
  inflating: weather_turkey_processed/38_38.csv
  inflating: weather_turkey_processed/38_39.5.csv
  inflating: weather_turkey_processed/38_39.csv
  inflating: weather_turkey_processed/38_40.5.csv
  inflating: weather_turkey_processed/38_40.csv
  inflating: weather_turkey_processed/38_41.5.csv
  inflating: weather_turkey_processed/38_41.csv
  inflating: weather_turkey_processed/38_42.5.csv
  inflating: weather_turkey_processed/38_42.csv
  inflating: weather_turkey_processed/38_43.5.csv
  inflating: weather_turkey_processed/38_43.csv
  inflating: weather_turkey_processed/38_44.5.csv
  inflating: weather_turkey_processed/38_44.csv
  inflating: weather_turkey_processed/38_45.csv
  inflating: weather_turkey_processed/38.5_26.5.csv
  inflating: weather_turkey_processed/38.5_26.csv
  inflating: weather_turkey_processed/38.5_27.5.csv
  inflating: weather_turkey_processed/38.5_27.csv
  inflating: weather_turkey_processed/38.5_28.5.csv
  inflating: weather_turkey_processed/38.5_28.csv
  inflating: weather_turkey_processed/38.5_29.5.csv
  inflating: weather_turkey_processed/38.5_29.csv
  inflating: weather_turkey_processed/38.5_30.5.csv
  inflating: weather_turkey_processed/38.5_30.csv
  inflating: weather_turkey_processed/38.5_31.5.csv
  inflating: weather_turkey_processed/38.5_31.csv
  inflating: weather_turkey_processed/38.5_32.5.csv
  inflating: weather_turkey_processed/38.5_32.csv
  inflating: weather_turkey_processed/38.5_33.5.csv
  inflating: weather_turkey_processed/38.5_33.csv
  inflating: weather_turkey_processed/38.5_34.5.csv
  inflating: weather_turkey_processed/38.5_34.csv
  inflating: weather_turkey_processed/38.5_35.5.csv
  inflating: weather_turkey_processed/38.5_35.csv
  inflating: weather_turkey_processed/38.5_36.5.csv
  inflating: weather_turkey_processed/38.5_36.csv
  inflating: weather_turkey_processed/38.5_37.5.csv
  inflating: weather_turkey_processed/38.5_37.csv
  inflating: weather_turkey_processed/38.5_38.5.csv
  inflating: weather_turkey_processed/38.5_38.csv
  inflating: weather_turkey_processed/38.5_39.5.csv
  inflating: weather_turkey_processed/38.5_39.csv
  inflating: weather_turkey_processed/38.5_40.5.csv
  inflating: weather_turkey_processed/38.5_41.5.csv
  inflating: weather_turkey_processed/38.5_41.csv
  inflating: weather_turkey_processed/38.5_42.5.csv
  inflating: weather_turkey_processed/42_43.5.csv
  inflating: weather_turkey_processed/38.5_43.5.csv
  inflating: weather_turkey_processed/38.5_43.csv
  inflating: weather_turkey_processed/38.5_44.5.csv
  inflating: weather_turkey_processed/38.5_44.csv
  inflating: weather_turkey_processed/38.5_45.csv
  inflating: weather_turkey_processed/39_26.5.csv
  inflating: weather_turkey_processed/39_26.csv
  inflating: weather_turkey_processed/39_27.5.csv
  inflating: weather_turkey_processed/39_27.csv
  inflating: weather_turkey_processed/39_28.5.csv
  inflating: weather_turkey_processed/39_28.csv
  inflating: weather_turkey_processed/39_29.5.csv
  inflating: weather_turkey_processed/39_29.csv
  inflating: weather_turkey_processed/39_30.5.csv
  inflating: weather_turkey_processed/39_30.csv
  inflating: weather_turkey_processed/39_31.5.csv
  inflating: weather_turkey_processed/39_31.csv
  inflating: weather_turkey_processed/39_32.5.csv
  inflating: weather_turkey_processed/39_32.csv
  inflating: weather_turkey_processed/39_33.5.csv
  inflating: weather_turkey_processed/39_33.csv
  inflating: weather_turkey_processed/39_34.5.csv
  inflating: weather_turkey_processed/39_34.csv
  inflating: weather_turkey_processed/39_35.5.csv
  inflating: weather_turkey_processed/39_35.csv
  inflating: weather_turkey_processed/39_36.5.csv
  inflating: weather_turkey_processed/39_36.csv
  inflating: weather_turkey_processed/39_37.5.csv
  inflating: weather_turkey_processed/39_37.csv
  inflating: weather_turkey_processed/39_38.5.csv
  inflating: weather_turkey_processed/39_38.csv
  inflating: weather_turkey_processed/39_39.5.csv
  inflating: weather_turkey_processed/39_39.csv
  inflating: weather_turkey_processed/39_40.5.csv
  inflating: weather_turkey_processed/39_40.csv
  inflating: weather_turkey_processed/39_41.5.csv
  inflating: weather_turkey_processed/39_41.csv
  inflating: weather_turkey_processed/39_42.5.csv
  inflating: weather_turkey_processed/39_42.csv
  inflating: weather_turkey_processed/39_43.5.csv
  inflating: weather_turkey_processed/39_43.csv
  inflating: weather_turkey_processed/39_44.5.csv
  inflating: weather_turkey_processed/39_44.csv
  inflating: weather_turkey_processed/39_45.csv
  inflating: weather_turkey_processed/39.5_26.5.csv
  inflating: weather_turkey_processed/39.5_26.csv
  inflating: weather_turkey_processed/39.5_27.5.csv
  inflating: weather_turkey_processed/39.5_27.csv
  inflating: weather_turkey_processed/39.5_28.5.csv
  inflating: weather_turkey_processed/39.5_28.csv
  inflating: weather_turkey_processed/39.5_29.5.csv
  inflating: weather_turkey_processed/39.5_29.csv
  inflating: weather_turkey_processed/39.5_30.5.csv
  inflating: weather_turkey_processed/39.5_30.csv
  inflating: weather_turkey_processed/39.5_31.5.csv
  inflating: weather_turkey_processed/39.5_31.csv
  inflating: weather_turkey_processed/39.5_32.5.csv
  inflating: weather_turkey_processed/39.5_32.csv
  inflating: weather_turkey_processed/39.5_33.5.csv
  inflating: weather_turkey_processed/39.5_33.csv
  inflating: weather_turkey_processed/39.5_34.5.csv
  inflating: weather_turkey_processed/39.5_34.csv
  inflating: weather_turkey_processed/39.5_35.5.csv
  inflating: weather_turkey_processed/39.5_35.csv
  inflating: weather_turkey_processed/39.5_36.5.csv
  inflating: weather_turkey_processed/39.5_36.csv
  inflating: weather_turkey_processed/39.5_37.5.csv
  inflating: weather_turkey_processed/39.5_37.csv
  inflating: weather_turkey_processed/39.5_38.5.csv
  inflating: weather_turkey_processed/39.5_38.csv
  inflating: weather_turkey_processed/39.5_39.5.csv
  inflating: weather_turkey_processed/39.5_39.csv
  inflating: weather_turkey_processed/39.5_40.5.csv
  inflating: weather_turkey_processed/39.5_40.csv
  inflating: weather_turkey_processed/39.5_41.5.csv
  inflating: weather_turkey_processed/40_43.csv
  inflating: weather_turkey_processed/39.5_41.csv
  inflating: weather_turkey_processed/39.5_42.5.csv
  inflating: weather_turkey_processed/39.5_42.csv
  inflating: weather_turkey_processed/39.5_43.5.csv
  inflating: weather_turkey_processed/39.5_43.csv
  inflating: weather_turkey_processed/39.5_44.5.csv
  inflating: weather_turkey_processed/39.5_44.csv
  inflating: weather_turkey_processed/39.5_45.csv
  inflating: weather_turkey_processed/40_26.5.csv
  inflating: weather_turkey_processed/40_26.csv
  inflating: weather_turkey_processed/40_27.5.csv
  inflating: weather_turkey_processed/40_27.csv
  inflating: weather_turkey_processed/40_28.5.csv
  inflating: weather_turkey_processed/40_28.csv
  inflating: weather_turkey_processed/40_29.5.csv
  inflating: weather_turkey_processed/40_29.csv
  inflating: weather_turkey_processed/40_30.5.csv
  inflating: weather_turkey_processed/40_30.csv
  inflating: weather_turkey_processed/40_31.5.csv
  inflating: weather_turkey_processed/40_31.csv
  inflating: weather_turkey_processed/40_32.5.csv
  inflating: weather_turkey_processed/40_32.csv
  inflating: weather_turkey_processed/40_33.5.csv
  inflating: weather_turkey_processed/40_33.csv
  inflating: weather_turkey_processed/40_34.5.csv
  inflating: weather_turkey_processed/40_34.csv
  inflating: weather_turkey_processed/40_35.5.csv
  inflating: weather_turkey_processed/40_35.csv
  inflating: weather_turkey_processed/40_36.5.csv
  inflating: weather_turkey_processed/40_36.csv
  inflating: weather_turkey_processed/40_37.5.csv
  inflating: weather_turkey_processed/40_37.csv
  inflating: weather_turkey_processed/40_38.5.csv
  inflating: weather_turkey_processed/40_38.csv
  inflating: weather_turkey_processed/40_39.5.csv
  inflating: weather_turkey_processed/40_39.csv
  inflating: weather_turkey_processed/40_40.5.csv
  inflating: weather_turkey_processed/40_40.csv
  inflating: weather_turkey_processed/40_41.5.csv
  inflating: weather_turkey_processed/40_41.csv
  inflating: weather_turkey_processed/40_42.5.csv
  inflating: weather_turkey_processed/40_42.csv
  inflating: weather_turkey_processed/40_43.5.csv
  inflating: weather_turkey_processed/40_44.5.csv
  inflating: weather_turkey_processed/40_44.csv
  inflating: weather_turkey_processed/40_45.csv
  inflating: weather_turkey_processed/40.5_26.5.csv
  inflating: weather_turkey_processed/40.5_26.csv
  inflating: weather_turkey_processed/40.5_27.5.csv
  inflating: weather_turkey_processed/40.5_27.csv
  inflating: weather_turkey_processed/40.5_28.csv
  inflating: weather_turkey_processed/40.5_29.5.csv
  inflating: weather_turkey_processed/40.5_29.csv
  inflating: weather_turkey_processed/40.5_30.5.csv
  inflating: weather_turkey_processed/40.5_30.csv
  inflating: weather_turkey_processed/40.5_31.5.csv
  inflating: weather_turkey_processed/40.5_31.csv
  inflating: weather_turkey_processed/40.5_32.5.csv
  inflating: weather_turkey_processed/40.5_32.csv
  inflating: weather_turkey_processed/40.5_33.5.csv
  inflating: weather_turkey_processed/40.5_33.csv
  inflating: weather_turkey_processed/40.5_34.5.csv
  inflating: weather_turkey_processed/40.5_34.csv
  inflating: weather_turkey_processed/40.5_35.5.csv
  inflating: weather_turkey_processed/40.5_35.csv
  inflating: weather_turkey_processed/40.5_36.5.csv
  inflating: weather_turkey_processed/40.5_36.csv
  inflating: weather_turkey_processed/40.5_37.5.csv
  inflating: weather_turkey_processed/40.5_37.csv
  inflating: weather_turkey_processed/40.5_38.5.csv
  inflating: weather_turkey_processed/40.5_38.csv
  inflating: weather_turkey_processed/40.5_39.5.csv
  inflating: weather_turkey_processed/40.5_39.csv
  inflating: weather_turkey_processed/40.5_40.5.csv
  inflating: weather_turkey_processed/40.5_40.csv
  inflating: weather_turkey_processed/40.5_41.5.csv
  inflating: weather_turkey_processed/40.5_41.csv
  inflating: weather_turkey_processed/40.5_42.5.csv
  inflating: weather_turkey_processed/40.5_42.csv
  inflating: weather_turkey_processed/40.5_43.5.csv
  inflating: weather_turkey_processed/40.5_43.csv
  inflating: weather_turkey_processed/40.5_44.5.csv
  inflating: weather_turkey_processed/40.5_44.csv
  inflating: weather_turkey_processed/40.5_45.csv
  inflating: weather_turkey_processed/41_26.5.csv
  inflating: weather_turkey_processed/41_26.csv
  inflating: weather_turkey_processed/41_27.5.csv
  inflating: weather_turkey_processed/41_27.csv
  inflating: weather_turkey_processed/41_28.5.csv
  inflating: weather_turkey_processed/41_28.csv
  inflating: weather_turkey_processed/41_29.5.csv

In [0]:
shutil.copy("drive/My Drive/colab_datas/IE 492/UECM-15012015-20022020.csv","./")
shutil.copy("drive/My Drive/colab_datas/IE 492/RealTimeConsumption-01122014-09032020.csv","./")
shutil.copy("drive/My Drive/colab_datas/IE 492/all_data.feather","./")

'./all_data.feather'

In [0]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import pandas_profiling
%matplotlib inline
from tqdm import tqdm_notebook as tqdm

In [0]:
weather_paths=glob.glob("weather_turkey_processed/*.csv")
np.random.choice(weather_paths,10)

array(['weather_turkey_processed/36.5_29.csv',
       'weather_turkey_processed/37_30.csv',
       'weather_turkey_processed/38_39.5.csv',
       'weather_turkey_processed/38_33.csv',
       'weather_turkey_processed/42_33.5.csv',
       'weather_turkey_processed/38.5_33.csv',
       'weather_turkey_processed/36_40.5.csv',
       'weather_turkey_processed/37.5_29.csv',
       'weather_turkey_processed/40.5_35.csv',
       'weather_turkey_processed/40_36.csv'], dtype='<U38')

In [0]:
# weather_turkey=pd.DataFrame()
# for path in tqdm(weather_paths):
#     df=pd.read_csv(path)
#     weather_turkey=pd.concat([weather_turkey,df]).reset_index(drop=True)
# weather_turkey

In [0]:
# weather_turkey.to_feather("drive/My Drive/colab_datas/IE 492/all_data.feather")

# Energy consumption

In [0]:
# bruuuuuuuh
consumption_df=pd.read_csv("RealTimeConsumption-01122014-09032020.csv",encoding='latin-1')
consumption_df.columns=["Date","Hour","Consumption"]
consumption_df["Datetime"]=consumption_df["Date"]+" "+consumption_df["Hour"]
consumption_df["Consumption"]=consumption_df["Consumption"].apply(lambda x:x.replace(",","")).astype(float)
consumption_df["Datetime"]=pd.to_datetime(consumption_df["Datetime"],format="%d.%m.%Y %H:%M")
consumption_df

             Date   Hour  Consumption            Datetime
0      31.12.2015  00:00     29590.88 2015-12-31 00:00:00
1      31.12.2015  01:00     27785.43 2015-12-31 01:00:00
2      31.12.2015  02:00     26516.53 2015-12-31 02:00:00
3      31.12.2015  03:00     26091.62 2015-12-31 03:00:00
4      31.12.2015  04:00     25871.54 2015-12-31 04:00:00
...           ...    ...          ...                 ...
36715  09.03.2020  19:00         0.00 2020-03-09 19:00:00
36716  09.03.2020  20:00         0.00 2020-03-09 20:00:00
36717  09.03.2020  21:00         0.00 2020-03-09 21:00:00
36718  09.03.2020  22:00         0.00 2020-03-09 22:00:00
36719  09.03.2020  23:00         0.00 2020-03-09 23:00:00

[36720 rows x 4 columns]

In [0]:
## bruuuuuuuh
#consumption_df=pd.read_csv("UECM-15012015-20022020.csv",encoding='latin-1')
#consumption_df.columns=["Date","Hour","Consumption"]
#consumption_df["Datetime"]=consumption_df["Date"]+" "+consumption_df["Hour"]
#consumption_df["Datetime"]=pd.to_datetime(consumption_df["Datetime"])
#consumption_df.Consumption=consumption_df.Consumption.apply(lambda x: x.replace(".","").replace(",",".")).astype(float)
#consumption_df

In [0]:
consumption_df=consumption_df.loc[consumption_df["Datetime"]<pd.to_datetime("2020-03-01 00:00:00")]
consumption_df

             Date   Hour  Consumption            Datetime
0      31.12.2015  00:00     29590.88 2015-12-31 00:00:00
1      31.12.2015  01:00     27785.43 2015-12-31 01:00:00
2      31.12.2015  02:00     26516.53 2015-12-31 02:00:00
3      31.12.2015  03:00     26091.62 2015-12-31 03:00:00
4      31.12.2015  04:00     25871.54 2015-12-31 04:00:00
...           ...    ...          ...                 ...
36499  29.02.2020  19:00     37673.62 2020-02-29 19:00:00
36500  29.02.2020  20:00     36701.12 2020-02-29 20:00:00
36501  29.02.2020  21:00     35761.05 2020-02-29 21:00:00
36502  29.02.2020  22:00     34614.46 2020-02-29 22:00:00
36503  29.02.2020  23:00     33287.72 2020-02-29 23:00:00

[36504 rows x 4 columns]

# Weather related features

pivotalyıp kaydet sonradan birleştirerek oku

### all data pivot

In [0]:
all_data=pd.read_feather("all_data.feather")
all_data

         model_type  model_epoch  ...  VGRD_planetary.boundary.layer  VIS_surface
0           gfs-025   1421280000  ...                       -5.30000          NaN
1           gfs-025   1421280000  ...                       -4.60000          NaN
2           gfs-025   1421301600  ...                       -2.20000          NaN
3           gfs-025   1421301600  ...                       -0.60000          NaN
4           gfs-025   1421323200  ...                       -0.40000          NaN
...             ...          ...  ...                            ...          ...
10813798    gfs-025   1582156800  ...                       -8.33064      24135.0
10813799    gfs-025   1582156800  ...                       -9.73074      24135.0
10813800    gfs-025   1582156800  ...                       -9.04956      24134.9
10813801    gfs-025   1582156800  ...                       -9.08133      24134.9
10813802    gfs-025   1582156800  ...                      -11.68630      24134.9

[10813803 rows x 45 columns]

In [0]:
# lat_lon=pd.DataFrame([i.strip(".csv").split("/")[-1].split("_") for i in weather_paths],columns=["lon","lat"]).astype(float).sort_values(by=["lon","lat"]).reset_index(drop=True)
# lat_lon

In [0]:
# all_data["forecast_epoch"]=pd.to_datetime(all_data["forecast_epoch"],unit="s")
# all_data=all_data.sort_values(by=["forecast_epoch"])
# all_data

In [0]:
all_data["CICEP_surface"].value_counts()

0.0    10811721
1.0          54
Name: CICEP_surface, dtype: int64

In [0]:
all_data=all_data.drop(columns=["model_type","model_epoch","CFRZR_surface","CICEP_surface","ICEC_surface","SNOD_surface"])
all_data

          forecast_epoch   lon  ...  VGRD_planetary.boundary.layer  VIS_surface
0             1421290800  35.0  ...                       -5.30000          NaN
1             1421301600  35.0  ...                       -4.60000          NaN
2             1421312400  35.0  ...                       -2.20000          NaN
3             1421323200  35.0  ...                       -0.60000          NaN
4             1421334000  35.0  ...                       -0.40000          NaN
...                  ...   ...  ...                            ...          ...
10813798      1582574400  26.0  ...                       -8.33064      24135.0
10813799      1582578000  26.0  ...                       -9.73074      24135.0
10813800      1582581600  26.0  ...                       -9.04956      24134.9
10813801      1582585200  26.0  ...                       -9.08133      24134.9
10813802      1582588800  26.0  ...                      -11.68630      24134.9

[10813803 rows x 39 columns]

In [0]:
# If sıkıntı cıkarsa
lat_lon_dict={"Istanbul":(41,29),
"Ankara":(40,33),
"Izmir":(38,27),
"Bursa":(40,29),
"Antalya":(37,30),
"Konya": (38,32)}
lat_lon_dict.values()

dict_values([(41, 29), (40, 33), (38, 27), (40, 29), (37, 30), (38, 32)])

In [0]:
lats_=np.array(list(lat_lon_dict.values()))[:,0]
long_=np.array(list(lat_lon_dict.values()))[:,1]

all_data=all_data.loc[(all_data["lat"].isin(lats_))]

In [0]:
all_data=all_data.loc[(all_data["lon"].isin(long_))]

In [0]:
weather_forecast_data=pd.pivot_table(all_data,index="forecast_epoch",columns=["lon","lat"])
weather_forecast_data.columns=['_'.join(list(map(str,i))) for i in weather_forecast_data.columns]

In [0]:
weather_forecast_data

                ACPCP_surface_27.0_37.0  ...  VIS_surface_33.0_41.0
forecast_epoch                           ...
1421290800                        4.530  ...                    NaN
1421301600                        7.600  ...                    NaN
1421312400                        0.550  ...                    NaN
1421323200                        0.580  ...                    NaN
1421334000                        0.140  ...                    NaN
...                                 ...  ...                    ...
1582574400                       11.875  ...                89.4110
1582578000                       11.875  ...                98.9967
1582581600                       11.875  ...               230.1060
1582585200                       11.875  ...                96.0809
1582588800                       11.875  ...               105.7090

[21329 rows x 720 columns]

In [0]:
weather_forecast_data=weather_forecast_data.reset_index()
weather_forecast_data["forecast_epoch"]=pd.to_datetime(weather_forecast_data["forecast_epoch"],unit="s")
weather_forecast_data

           forecast_epoch  ...  VIS_surface_33.0_41.0
0     2015-01-15 03:00:00  ...                    NaN
1     2015-01-15 06:00:00  ...                    NaN
2     2015-01-15 09:00:00  ...                    NaN
3     2015-01-15 12:00:00  ...                    NaN
4     2015-01-15 15:00:00  ...                    NaN
...                   ...  ...                    ...
21324 2020-02-24 20:00:00  ...                89.4110
21325 2020-02-24 21:00:00  ...                98.9967
21326 2020-02-24 22:00:00  ...               230.1060
21327 2020-02-24 23:00:00  ...                96.0809
21328 2020-02-25 00:00:00  ...               105.7090

[21329 rows x 721 columns]

In [0]:
del all_data
weather_forecast_data=weather_forecast_data.interpolate(limit_direction="both")

In [0]:
weather_forecast_data

           forecast_epoch  ...  VIS_surface_33.0_41.0
0     2015-01-15 03:00:00  ...             20200.0000
1     2015-01-15 06:00:00  ...             20200.0000
2     2015-01-15 09:00:00  ...             20200.0000
3     2015-01-15 12:00:00  ...             20200.0000
4     2015-01-15 15:00:00  ...             20200.0000
...                   ...  ...                    ...
21324 2020-02-24 20:00:00  ...                89.4110
21325 2020-02-24 21:00:00  ...                98.9967
21326 2020-02-24 22:00:00  ...               230.1060
21327 2020-02-24 23:00:00  ...                96.0809
21328 2020-02-25 00:00:00  ...               105.7090

[21329 rows x 721 columns]

# comnt

In [0]:
weather_turkey_processed=pd.read_csv(weather_paths[0])

In [0]:
weather_turkey_processed["forecast_epoch"]=pd.to_datetime(weather_turkey_processed["forecast_epoch"],unit="s")
weather_turkey_processed=weather_turkey_processed.sort_values(by=["forecast_epoch"])
weather_turkey_processed

      model_type  model_epoch  ... VGRD_planetary.boundary.layer  VIS_surface
0        gfs-025   1421280000  ...                      2.600000          NaN
1        gfs-025   1421280000  ...                      2.300000          NaN
2        gfs-025   1421301600  ...                      2.200000          NaN
3        gfs-025   1421301600  ...                      1.400000          NaN
4        gfs-025   1421323200  ...                      2.300000          NaN
...          ...          ...  ...                           ...          ...
21324    gfs-025   1582156800  ...                      1.569360      24135.0
21325    gfs-025   1582156800  ...                      1.669260      24135.0
21326    gfs-025   1582156800  ...                      1.350440      21849.3
21327    gfs-025   1582156800  ...                      1.018670      21202.9
21328    gfs-025   1582156800  ...                      0.813739      12871.3

[21329 rows x 45 columns]

In [0]:
weather_turkey_processed.forecast_epoch.value_counts()

2018-08-01 12:00:00    1
2017-05-16 12:00:00    1
2019-05-02 10:00:00    1
2019-05-25 21:00:00    1
2016-09-06 18:00:00    1
                      ..
2018-07-21 15:00:00    1
2017-10-16 06:00:00    1
2016-04-22 18:00:00    1
2019-02-06 04:00:00    1
2017-07-24 03:00:00    1
Name: forecast_epoch, Length: 21329, dtype: int64

In [0]:
weather_turkey_processed.isna().sum()

model_type                                                  0
model_epoch                                                 0
forecast_epoch                                              0
lon                                                         0
lat                                                         0
ACPCP_surface                                               4
ALBDO_surface                                               4
APCP_surface                                                4
CFRZR_surface                                               4
CICEP_surface                                               4
CPRAT_surface                                               4
CRAIN_surface                                               4
CSNOW_surface                                               4
DLWRF_surface                                               4
DPT_2.m.above.ground                                        4
DSWRF_surface                                               4
GUST_surface                                                0
ICEC_surface                                                4
PRATE_surface                                               4
PRES_80.m.above.ground                                      4
PRES_surface                                                4
PRMSL_mean.sea.level                                        4
PWAT_entire.atmosphere..considered.as.a.single.layer.       4
RH_2.m.above.ground                                         4
RH_entire.atmosphere..considered.as.a.single.layer.         4
SNOD_surface                                                4
SUNSD_surface                                               4
TCDC_boundary.layer.cloud.layer                             4
TCDC_convective.cloud.layer                                 4
TCDC_entire.atmosphere                                      4
TCDC_high.cloud.layer                                       4
TCDC_low.cloud.layer                                        4
TCDC_middle.cloud.layer                                     4
TMP_2.m.above.ground                                        4
TMP_80.m.above.ground                                       4
TMP_surface                                                 4
UGRD_10.m.above.ground                                      4
UGRD_80.m.above.ground                                      4
UGRD_planetary.boundary.layer                               0
USWRF_surface                                               4
USWRF_top.of.atmosphere                                    90
VGRD_10.m.above.ground                                      4
VGRD_80.m.above.ground                                      4
VGRD_planetary.boundary.layer                               0
VIS_surface                                              8654
dtype: int64

In [0]:
weather_turkey_processed=weather_turkey_processed.drop(columns=["model_type","lon","lat","model_epoch","VIS_surface","CFRZR_surface","CICEP_surface","ICEC_surface"])
weather_turkey_processed

           forecast_epoch  ...  VGRD_planetary.boundary.layer
0     2015-01-15 03:00:00  ...                       2.600000
1     2015-01-15 06:00:00  ...                       2.300000
2     2015-01-15 09:00:00  ...                       2.200000
3     2015-01-15 12:00:00  ...                       1.400000
4     2015-01-15 15:00:00  ...                       2.300000
...                   ...  ...                            ...
21324 2020-02-24 20:00:00  ...                       1.569360
21325 2020-02-24 21:00:00  ...                       1.669260
21326 2020-02-24 22:00:00  ...                       1.350440
21327 2020-02-24 23:00:00  ...                       1.018670
21328 2020-02-25 00:00:00  ...                       0.813739

[21329 rows x 37 columns]

In [0]:
weather_turkey_processed=weather_turkey_processed.interpolate()

In [0]:
weather_turkey_processed.isna().sum()

forecast_epoch                                           0
ACPCP_surface                                            0
ALBDO_surface                                            0
APCP_surface                                             0
CPRAT_surface                                            0
CRAIN_surface                                            0
CSNOW_surface                                            0
DLWRF_surface                                            0
DPT_2.m.above.ground                                     0
DSWRF_surface                                            0
GUST_surface                                             0
PRATE_surface                                            0
PRES_80.m.above.ground                                   0
PRES_surface                                             0
PRMSL_mean.sea.level                                     0
PWAT_entire.atmosphere..considered.as.a.single.layer.    0
RH_2.m.above.ground                                      0
RH_entire.atmosphere..considered.as.a.single.layer.      0
SNOD_surface                                             0
SUNSD_surface                                            0
TCDC_boundary.layer.cloud.layer                          0
TCDC_convective.cloud.layer                              0
TCDC_entire.atmosphere                                   0
TCDC_high.cloud.layer                                    0
TCDC_low.cloud.layer                                     0
TCDC_middle.cloud.layer                                  0
TMP_2.m.above.ground                                     0
TMP_80.m.above.ground                                    0
TMP_surface                                              0
UGRD_10.m.above.ground                                   0
UGRD_80.m.above.ground                                   0
UGRD_planetary.boundary.layer                            0
USWRF_surface                                            0
USWRF_top.of.atmosphere                                  0
VGRD_10.m.above.ground                                   0
VGRD_80.m.above.ground                                   0
VGRD_planetary.boundary.layer                            0
dtype: int64

In [0]:
weather_turkey_processed

           forecast_epoch  ...  VGRD_planetary.boundary.layer
0     2015-01-15 03:00:00  ...                       2.600000
1     2015-01-15 06:00:00  ...                       2.300000
2     2015-01-15 09:00:00  ...                       2.200000
3     2015-01-15 12:00:00  ...                       1.400000
4     2015-01-15 15:00:00  ...                       2.300000
...                   ...  ...                            ...
21324 2020-02-24 20:00:00  ...                       1.569360
21325 2020-02-24 21:00:00  ...                       1.669260
21326 2020-02-24 22:00:00  ...                       1.350440
21327 2020-02-24 23:00:00  ...                       1.018670
21328 2020-02-25 00:00:00  ...                       0.813739

[21329 rows x 37 columns]

In [0]:
#weather_html=pandas_profiling.ProfileReport(weather_turkey_processed)
#weather_html.to_file("train.html")

In [0]:
cons_temp=pd.merge(consumption_df,weather_turkey_processed,left_on="Datetime",right_on="forecast_epoch",how="left").interpolate(limit_direction="both")
cons_temp.drop(columns=["forecast_epoch"],inplace=True)

In [0]:
weather_turkey_processed

           forecast_epoch  ...  VGRD_planetary.boundary.layer
0     2015-01-15 03:00:00  ...                       2.600000
1     2015-01-15 06:00:00  ...                       2.300000
2     2015-01-15 09:00:00  ...                       2.200000
3     2015-01-15 12:00:00  ...                       1.400000
4     2015-01-15 15:00:00  ...                       2.300000
...                   ...  ...                            ...
21324 2020-02-24 20:00:00  ...                       1.569360
21325 2020-02-24 21:00:00  ...                       1.669260
21326 2020-02-24 22:00:00  ...                       1.350440
21327 2020-02-24 23:00:00  ...                       1.018670
21328 2020-02-25 00:00:00  ...                       0.813739

[21329 rows x 37 columns]

In [0]:
shu

NameError: ignored

In [0]:
for path in tqdm(weather_paths):
    weather_turkey_processed=pd.read_csv(path)
    lat_lon=path.strip(".csv").split("/")[-1]
    weather_turkey_processed["forecast_epoch"]=pd.to_datetime(weather_turkey_processed["forecast_epoch"],unit="s")
    weather_turkey_processed=weather_turkey_processed.sort_values(by=["forecast_epoch"])
    weather_turkey_processed=weather_turkey_processed.drop(columns=["model_type","lon","lat","model_epoch","VIS_surface","CFRZR_surface","CICEP_surface","ICEC_surface"])
    weather_turkey_processed.columns=[lat_lon+"-"+col for col in weather_turkey_processed.columns]
    consumption_df=pd.merge(consumption_df,weather_turkey_processed,left_on="Datetime",right_on=lat_lon+"-forecast_epoch",how="left").interpolate(limit_direction="both")
    consumption_df.drop(columns=[lat_lon+"-forecast_epoch"],inplace=True)

In [0]:
weather_turkey_processed

# Merge

In [0]:
cons_temp=pd.merge(consumption_df,weather_forecast_data,left_on="Datetime",right_on="forecast_epoch",how="left")
cons_temp.set_index("Datetime",inplace=True)
cons_temp=cons_temp.interpolate(method="time", limit_direction="both")
cons_temp

In [0]:
cons_temp=cons_temp.drop(columns=["forecast_epoch"])

In [0]:
seasons = [1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 1]
month_to_season = dict(zip(range(1,13), seasons))

In [0]:
cons_temp["Hour"]=cons_temp["Hour"].apply(lambda x:x.split(":")[0]).astype(int)
cons_temp["Day"]=cons_temp["Date"].apply(lambda x:x.split(".")[0]).astype(int)
cons_temp["Month"]=cons_temp["Date"].apply(lambda x:x.split(".")[1]).astype(int)
cons_temp["Year"]=cons_temp["Date"].apply(lambda x:x.split(".")[2]).astype(int)
cons_temp["weekday"]=pd.to_datetime(cons_temp["Date"]).apply(lambda x: x.weekday()).astype(int)# sonradan eklendi kaldırıp performans testin yab
cons_temp["Season"]=cons_temp["Month"].map(month_to_season)# sonradan sonradan eklendi perf test
cons_temp["Quarter"]=pd.to_datetime(cons_temp["Date"]).dt.to_period("Q")
# quarter ekle

In [0]:
cons_temp['Hour_sin'] = np.sin(2 * np.pi * cons_temp['Hour']/23.0)
cons_temp['Hour_cos'] = np.cos(2 * np.pi * cons_temp['Hour']/23.0)

cons_temp['Day_sin'] = np.sin(2 * np.pi * cons_temp['Day']/31.0)
cons_temp['Day_cos'] = np.cos(2 * np.pi * cons_temp['Day']/31.0)

cons_temp['Month_sin'] = np.sin(2 * np.pi * cons_temp['Month']/12.0)
cons_temp['Month_cos'] = np.cos(2 * np.pi * cons_temp['Month']/12.0)

cons_temp['weekday_sin'] = np.sin(2 * np.pi * cons_temp['weekday']/6.0)
cons_temp['weekday_cos'] = np.cos(2 * np.pi * cons_temp['weekday']/6.0)

# SEASON VE QUARTER CYCLIC

del cons_temp["Date"]

# Scaling

In [0]:
#from sklearn.preprocessing import scale
#non_scaled_features=["Consumption","Hour","Day","Month","Year","weekday","Season","Quarter","Hour_sin","Hour_cos","Day_sin","Day_cos","Month_sin","Month_cos","weekday_sin","weekday_cos"]
#cons_temp[cons_temp.columns.difference(non_scaled_features)]=pd.DataFrame(scale(cons_temp[cons_temp.columns.difference(non_scaled_features)]),columns=cons_temp[cons_temp.columns.difference(non_scaled_features)].columns)
# bir işe yaramadı

# Shift

In [0]:
# buraya shift koyuyorum
# model trainlensin sonra

# Create validation part of the data

In [0]:
# buraya 2020nin ocagı dataya eklenip sonrası validation datası olarak kullanılacak
cons_temp=cons_temp.reset_index()
train_range=cons_temp.loc[cons_temp.Datetime < pd.to_datetime("20200120",format="%Y%m%d")].index
validation_range=cons_temp.loc[cons_temp.Datetime >= pd.to_datetime("20200120",format="%Y%m%d")].index
del cons_temp["Datetime"]
train_range

# Data Prep

In [0]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack

cat_features=["Hour","Day","Month","weekday","Quarter","Season"]
linear_enc=OneHotEncoder()
one_hot_encoded=linear_enc.fit_transform(cons_temp[cat_features]).toarray()
train_df=hstack([cons_temp[cons_temp.columns.difference(cat_features)].astype(float).drop(columns=["Consumption"]),one_hot_encoded])

In [0]:
valid_df=train_df.toarray()[validation_range]
valid_y=cons_temp["Consumption"][validation_range]
train_df=train_df.toarray()[train_range]
train_y=cons_temp["Consumption"][train_range]

# Linear Regression

### Training

In [0]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(train_df,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(valid_df)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(train_df)
sns.scatterplot(x=preds,y=train_y,ax=ax[0])
sns.residplot(preds, train_y,ax=ax[1])

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(valid_df)
sns.scatterplot(x=preds,y=valid_y,ax=ax[0])
sns.residplot(preds, valid_y,ax=ax[1])

# Ridge

In [0]:
from sklearn.linear_model import Ridge

model=Ridge()
model.fit(train_df,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(valid_df)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(train_df)
sns.scatterplot(x=preds,y=train_y,ax=ax[0])
sns.residplot(preds, train_y,ax=ax[1])

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(valid_df)
sns.scatterplot(x=preds,y=valid_y,ax=ax[0])
sns.residplot(preds, valid_y,ax=ax[1])

# Lasso

In [0]:
from sklearn.linear_model import Lasso

model=Lasso(alpha=1)
model.fit(train_df,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(valid_df)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(train_df)
sns.scatterplot(x=preds,y=train_y,ax=ax[0])
sns.residplot(preds, train_y,ax=ax[1])

In [0]:
fig,ax=plt.subplots(nrows=2,figsize=(15,15))
preds=model.predict(valid_df)
sns.scatterplot(x=preds,y=valid_y,ax=ax[0])
sns.residplot(preds, valid_y,ax=ax[1])

# Feature selector

In [0]:
!pip install feature-selector

In [0]:
from feature_selector import FeatureSelector
fs = FeatureSelector(data = pd.DataFrame(train_df), labels = train_y)
fs.identify_zero_importance(task = 'regression', eval_metric = 'mse', 
                            n_iterations = 5, early_stopping = True)

# RFE

In [0]:
from sklearn.feature_selection import RFE

In [0]:
selector = RFE(model, 600, step=5)
selector = selector.fit(train_df, train_y)
selector.support_

In [0]:
selector.ranking_

In [0]:
np.where(selector.support_)[0]

In [0]:
from sklearn.linear_model import Lasso

model=Lasso()
model.fit(pd.DataFrame(train_df)[np.where(selector.support_)[0]].values,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(pd.DataFrame(valid_df)[np.where(selector.support_)[0]].values)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))

# OLS

In [0]:
from sklearn.datasets import load_boston
import pandas as pd
import numpy as np
import statsmodels.api as sm

data = load_boston()
X = pd.DataFrame(train_df.copy())
y = train_y.values.copy()


def stepwise_selection(X, y, 
                       initial_list=[], 
                       threshold_in=0.01, 
                       threshold_out = 0.05, 
                       verbose=True):
    """ Perform a forward-backward feature selection 
    based on p-value from statsmodels.api.OLS
    Arguments:
        X - pandas.DataFrame with candidate features
        y - list-like with the target
        initial_list - list of features to start with (column names of X)
        threshold_in - include a feature if its p-value < threshold_in
        threshold_out - exclude a feature if its p-value > threshold_out
        verbose - whether to print the sequence of inclusions and exclusions
    Returns: list of selected features 
    Always set threshold_in < threshold_out to avoid infinite looping.
    See https://en.wikipedia.org/wiki/Stepwise_regression for the details
    """
    included = list(initial_list)
    while True:
        changed=False
        # forward step
        excluded = list(set(X.columns)-set(included))
        new_pval = pd.Series(index=excluded)
        for new_column in excluded:
            model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included+[new_column]]))).fit()
            new_pval[new_column] = model.pvalues[new_column]
        best_pval = new_pval.min()
        if best_pval < threshold_in:
            best_feature = new_pval.argmin()
            included.append(best_feature)
            changed=True
            if verbose:
                print('Add  {:30} with p-value {:.6}'.format(best_feature, best_pval))

        # backward step
        model = sm.OLS(y, sm.add_constant(pd.DataFrame(X[included]))).fit()
        # use all coefs except intercept
        pvalues = model.pvalues.iloc[1:]
        worst_pval = pvalues.max() # null if pvalues is empty
        if worst_pval > threshold_out:
            changed=True
            worst_feature = pvalues.argmax()
            included.remove(worst_feature)
            if verbose:
                print('Drop {:30} with p-value {:.6}'.format(worst_feature, worst_pval))
        if not changed:
            break
    return included

result = stepwise_selection(X, y)

print('resulting features:')
print(result)

# Lag addition

In [0]:
cons_temp["two_days_lag"]=cons_temp.Consumption.shift(24*2)
cons_temp["seven_days_lag"]=cons_temp.Consumption.shift(24*7)
cons_temp.dropna(inplace=True)

###  Create validation part of the data

In [0]:
# buraya 2020nin ocagı dataya eklenip sonrası validation datası olarak kullanılacak
cons_temp=cons_temp.reset_index()
train_range=cons_temp.loc[cons_temp.Datetime < pd.to_datetime("20200120",format="%Y%m%d")].index
validation_range=cons_temp.loc[cons_temp.Datetime >= pd.to_datetime("20200120",format="%Y%m%d")].index
del cons_temp["Datetime"]
train_range

# Drop forecasts lag and reduce dimensions

In [0]:
only_lag=["Hour","Consumption","Day","Month","Year","weekday","Season","Quarter","Hour_sin","Hour_cos","Day_sin","Day_cos","Month_sin","Month_cos","weekday_sin","weekday_cos","two_days_lag","seven_days_lag"]
#cons_temp=cons_temp[only_lag]

In [0]:
from sklearn.decomposition import PCA
pca = PCA()
pca.fit(cons_temp[cons_temp.columns.difference(only_lag)])

In [0]:
sum(pca.explained_variance_ratio_[:30])

In [0]:
cons_pca=pca.transform(cons_temp[cons_temp.columns.difference(only_lag)])[:,:30]

In [0]:
cons_temp=pd.DataFrame(np.hstack([cons_temp[only_lag],cons_pca]),columns=only_lag+["pca_"+str(i) for i in range(1,31)])

# Data Prep

In [0]:
from sklearn.preprocessing import OneHotEncoder
from scipy.sparse import hstack

cat_features=["Hour","Day","Month","weekday","Quarter","Season"]
linear_enc=OneHotEncoder()
one_hot_encoded=linear_enc.fit_transform(cons_temp[cat_features]).toarray()
train_df=hstack([cons_temp[cons_temp.columns.difference(cat_features)].astype(float).drop(columns=["Consumption"]),one_hot_encoded])

In [0]:
valid_df=train_df.toarray()[validation_range]
valid_y=cons_temp["Consumption"][validation_range]
train_df=train_df.toarray()[train_range]
train_y=cons_temp["Consumption"][train_range]

# Linear Regression

### Training

In [0]:
train_df.shape

In [0]:
from sklearn.linear_model import LinearRegression

model=LinearRegression()
model.fit(train_df,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(valid_df)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))

In [0]:
(1855.9812806317311, 0.053833315279816364)
(1831.0446551050575, 0.05323971258223524)

In [0]:
cons_temp

# Lasso

In [0]:
from sklearn.linear_model import Lasso

model=Lasso(alpha=1)
model.fit(train_df,train_y)

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(train_df)
np.sqrt(mean_squared_error(pred,train_y.values)),np.sqrt(mean_squared_log_error(pred,train_y.values))

In [0]:
from sklearn.metrics import mean_squared_error,mean_squared_log_error
pred=model.predict(valid_df)
np.sqrt(mean_squared_error(pred,valid_y.values)),np.sqrt(mean_squared_log_error(pred,valid_y.values))